# name project
spring.application.name=rungroop

# server
server.port=8080

# conexion jdbc a postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/rungroop_db
spring.datasource.username=wreckcode
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# configuracion hibernate / jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
